### ISSUE TITLE
Fix Bugs Related To Path of thyra-server

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/Thyra-Menu-Bar-App#25]
**Describe the bug**
The bug comes when the ThyraApp cannot find the correct path in the path.txt file created in the .config folder

**To Reproduce**

1. Install Thyra froml the script located in scripts/thyra-installer.py https://github.com/massalabs/thyra/pull/392
2. launch the thyraApp downloaded at your home, and check if it creates a new path.txt at your .config
3. check the content of the path.txt if its correct it should looks like echo $PATH RESULT
4. launch ThyraApp and check if its launched correctly without any error msg

**Screenshots**
We are facing this issue with some windows users who have special characters inside their windows username , so it creates some path.txt with `?`instead of `é`for example 
![image](https://user-images.githubusercontent.com/16125633/211768736-bee82336-7df7-4cc5-8c4d-f3c730fda675.png)

**Technical details*
1- to launch thyra-server from thyra we are using python command  `which("thyra-server")`to retrieve the path of the installed `thyra-server` , at the runtime of the application this command  returns None, so we are using a hook file path.py  or path.sh which exports the env variable $PATH and put it in a file located at config/path.txt.  
2- so after running the hook file, we start the app, we set the env variable to the one stored in path.txt, and we can expect 
`which("thyra-server")` to return a correct path to thyra-server.   
3- All you need to do is check that which `which("thyra-server")` returns a valid pass if you have a better way to do it we remove this hook file strategy   
line 98 : https://github.com/massalabs/Thyra-Menu-Bar-App/blob/main/thyra_app.py. 
line 26 :  https://github.com/massalabs/Thyra-Menu-Bar-App/blob/main/utils/background_thyra_scripts.py.

**Comment by thomas-senechal** [comment]
![image](https://user-images.githubusercontent.com/44696378/213214944-280fcfdc-ae27-4c05-aeb4-fe7b250e6127.png)

Had a related error during Thyra-App launch after a fresh install.

**Comment by SlnPons** [comment]
@thomas-senechal I thin this bug was Windows related, could you confirm please? :) 
So that I can ask someone with Windows to QA it correctly.

**Comment by B-Naoufal** [comment]
@SlnPons yes and it was already correct and validated by @0xMazout as a windows user

**Comment by thomas-senechal** [comment]
@B-Naoufal @SlnPons Are we sure the bug related to accents such as `é` has been resolved ? 

This bug is mentionned in this issue. We closed this issue as completed following #27 , but AFAIK, #27 didn't fixed this issue.

I think we need someone that experienced this issue to test if it's working properly now. And if not, we should open a new issue focusing on this problem.

**Comment by SlnPons** [comment]
Ok, so @SebastienValla could you test Thyra app installation on your computer please? 
You should be able to do by following the step-by-step described here: https://github.com/massalabs/thyra/blob/main/INSTALLATION.md#windows

**Comment by B-Naoufal** [comment]
@thomas-senechal yes my last merge should fix also the è character since i am not using only the path.txt to fuess the locationof thyra-server,we know in advance that the thyra-server will be stored in the home of any user after installing thyra, so i am using that as a ^python left OR^!

**Comment by SlnPons** [comment]
@B-Naoufal the fix for the accent hasn't been solved as Seb is still experiencing it today. 
This is _not_ normal. The comments on this ticket asked clearly the question but once again we assume things without testing them correctly. The job is not done correctly.

The expected job is to: put the ticket in QA, ask appropriate PM or dev to QA the ticket end-to-end correctly, here the fix you did is wider that the bug mentioned however EVERYTHING needs to be tested. Once everything is tested, come back to PM to put this ticket in done.


If this problem kind of problems happens one more time, the trust will be broken and I will be forced to change the way I worked with you by removing autonomy...
